Update dicom_to_nifti with a CLI
shimming-toolbox/shimming-toolbox pull request #120
Opened 2020-10-05 15:43 UTC by po09i

## Description
This PR adds a CLI for the dicom_to_nifti API. See the related issue #86 for the different options.
The PR also modifies the config file to be able to test it with realtime_zshimming_data. It adds the ability to use dicom_to_nifti with anatomical GREs and functional bold files.

TODO:
- [ ] dicom_to_nifti_cli
- [ ] Update config file
- [ ] Create test for new config file

## Linked issues
Fixes #86 
Fixes #112

2020-10-06 14:41 UTC, jidicula requested changes
Could you run the files through a formatting tool? If you have Black installed, you can do `black -S path/to/file` for each file (-S preserves the quote style for strings).

2020-10-06 14:41 UTC, jidicula commented on test/test_dicom_to_nifti.py
>      # TODO: put as decorator
Could add this as a refactor issue ticket and get rid of the TODO

2020-10-06 15:10 UTC, po09i commented
> Could you run the files through a formatting tool? If you have Black installed, you can do `black -S path/to/file` for each file (-S preserves the quote style for strings).

pycharm does it automatically, I double checked and everything seems good!

2020-10-06 15:20 UTC, jidicula approved these changes
LGTM!

2020-10-07 20:07 UTC, po09i commented
As discussed in internal meeting, call CLI tests cli/test_cli_XX

2020-10-08 22:35 UTC, jidicula approved these changes

2020-10-08 23:51 UTC, merged