Add GUI Integration into FSLeyes
shimming-toolbox/shimming-toolbox pull request #232
Opened 2021-02-25 18:48 UTC by ahill187

## Checklist

- [ ] I've given this PR a concise, self-descriptive, and meaningful title
- [ ] I've linked relevant issues in the PR body
- [ ] I've applied the relevant labels to this PR
- [ ] I've added relevant tests for my contribution
- [ ] I've updated the documentation and/or added correct docstrings
- [ ] I've assigned a reviewer

## Description

## Linked issues

2021-03-03 19:45 UTC, jcohenadad reviewed
I do prefer scripts, but open to discussion -- see https://github.com/shimming-toolbox/shimming-toolbox/issues/205#issuecomment-790006679

2021-03-03 20:48 UTC, jcohenadad commented
Few review comments (from most priority to least priority):
- implement feature of selecting "input files" that are listed in the overlay section of fsleyes
- "mask" card: i got this error: `no such option: -i`
- "fieldmap": for unwrapper: create a combo box listing the options 
- "fieldmap": we should be able to only select the folder containing the fieldmaps-- the function will figure out each phase files and the number of echos
- "dcm2niix" card: if output folder does not exist, it will crash.
- add more verbose in the Terminal

2021-03-08 21:24 UTC, po09i commented on shimmingtoolbox/utils.py
> +def create_output_dir(path_output, output_folder_name="output"):
```suggestion
def create_output_dir(path_output):
```

2021-03-08 21:24 UTC, po09i commented on shimmingtoolbox/utils.py
> +        output_folder_name (str): Name of sub-folder.
```suggestion

```

2021-03-12 05:43 UTC, po09i commented
`FSLEYES_PLUGIN_PATH` shell variable can be used to automatically load the newest version of the plugin. Only need to activate it to show it up.

2021-03-17 00:13 UTC, jcohenadad commented
hum, why is it looking there? i'm using https://github.com/shimming-toolbox/shimming-toolbox/pull/232/commits/c5775938811eb1dfc308ad571649ab8bbdcd8d68

![Screen Shot 2021-03-16 at 8 12 47 PM](https://user-images.githubusercontent.com/2482071/111395799-12957a80-8694-11eb-9d50-0238bc861cac.png)

2021-03-17 03:27 UTC, po09i commented
> hum, why is it looking there? i'm using [c577593](https://github.com/shimming-toolbox/shimming-toolbox/commit/c5775938811eb1dfc308ad571649ab8bbdcd8d68)

Since we can't import any shimming toolbox packages, we also can't import `__dir_shimmingtoolbox__`. Two things rely on this: the value for default paths and the logo. 
We defined `__dir_shimmingtoolbox__` like so:
`__dir_shimmingtoolbox__ = os.path.dirname(os.path.dirname(os.path.dirname(os.path.realpath(__file__))))`
I'm guessing it tried to use the GUI file that was in .fsleyes so it could not find the logo since it was the wrong shimming toolbox path.

The only solution I see is having a shell variable for Shimming Toolbox so that we can find the logo. However, I don't think this is relevant to fix since we want to move to a fsleyes package in #242 anyways and the package could include the logo and change the default paths to the current directory.

2021-03-17 03:30 UTC, po09i commented
It looks good to me but I was a big contributor so I'll wait for others to have a look.

2021-03-17 13:39 UTC, jcohenadad commented
> > hum, why is it looking there? i'm using [c577593](https://github.com/shimming-toolbox/shimming-toolbox/commit/c5775938811eb1dfc308ad571649ab8bbdcd8d68)
> 
> Since we can't import any shimming toolbox packages, we also can't import `__dir_shimmingtoolbox__`. Two things rely on this: the value for default paths and the logo.
> 
> We defined `__dir_shimmingtoolbox__` like so:
> `__dir_shimmingtoolbox__ = os.path.dirname(os.path.dirname(os.path.dirname(os.path.realpath(__file__))))` which works if the gui file is in the shimming toolbox repo. I'm guessing it tried to use the GUI file that was in .fsleyes so it could not find the logo since it was the wrong shimming toolbox path.
> 
> The only solution I see is having a shell variable for Shimming Toolbox so that we can find the logo. However, I don't think this is relevant to fix since we want to move to a fsleyes package in #242 anyways and the package will include the logo and change the default paths to the current directory.
> 
> PS: To test, I would remove the files in the .fsleyes directory, relaunch fsleyes, load the plugin but select "no" when prompted to permanently install since we are still in the dev stage. Hopefully it should work after that.

what i did:
- removed the file `~/.fsleyes/plugins/st_plugin.py`
- activated ST venv
- opened fsleyes
- re-loaded this plugin
- i get the same error

2021-03-18 20:07 UTC, gaspardcereza approved these changes
We tested everything from scratch and it worked (MacOs Catalina & Big Sur). Installation process will be updated once the new plugin repo will be working.

2021-03-19 19:36 UTC, po09i requested changes
Before merging in master, we should merge #242 in this branch and port to the new repo the gui files, then remove those files from this repo.

2021-03-20 02:19 UTC, closed without merging