Allow spaces in the CLIs
shimming-toolbox/shimming-toolbox pull request #387
Opened 2022-05-03 05:15 UTC by po09i

## Description
This PR adds the ability to have spaces in the input paths of the CLIs

2022-05-05 14:07 UTC, jcohenadad approved these changes
not tested, but nothing shocking and @po09i tested successfully

2022-05-05 15:31 UTC, kousu requested changes

2022-05-05 15:31 UTC, kousu commented on shimmingtoolbox/utils.py
> +        command = shlex.split(cmd)
dcm2bids actually [removed shlex](https://github.com/UNFmontreal/Dcm2Bids/pull/158/files#diff-269f9a2dff43a28dbadeda57cde6a9be58a1586ff0c4c69d36614c82b9a1dd71L120) to solve the same issue:

```diff
-    return check_output(shlex.split(commandLine))
+    return check_output(commandLine)
```

and replaced passing the command as a string with passing it as a list ([eg](https://github.com/UNFmontreal/Dcm2Bids/pull/158/files#diff-d02dd4a0ecc637d23f2a143ccc5c95aa749a5ec362bfb85133650c1de7e5c158L98))

```diff
-            commandTpl = "dcm2niix {} -o {} {}"
-            cmd = commandTpl.format(self.options, self.outputDir, dicomDir)
+            cmd = ['dcm2niix', *shlex.split(self.options),
+                   '-o', self.outputDir, dicomDir]
```

[or](https://github.com/UNFmontreal/Dcm2Bids/pull/158/files#diff-056f9fc95825035e71b1b7f0b37031326139ac5d3578135b82374cd7c4377c99L10)

```diff
-    "defaceTpl": "pydeface --outfile {dstFile} {srcFile}",
+    "defaceTpl": ["pydeface", "--outfile", "dstFile", "srcFile"],
```

(ultimately this is because the underlying C [execve(2)](https://manpages.ubuntu.com/manpages/jammy/en/man2/execve.2.html) call itself takes a list: `char *const argv[]`).

Passing a list is the only really reliable way to spawn subprocesses. This PR as it stands handles files with spaces in their name, but it will break in really confusing ways if a user manages to make a file with a `'` in its name, or maybe if they have a `'` in their username (and thus their `$HOME`).

2022-05-05 19:44 UTC, po09i commented on shimmingtoolbox/utils.py
> +        command = shlex.split(cmd)
Good point! I'll do the necessary changes

2022-05-05 21:13 UTC, kousu commented on shimmingtoolbox/utils.py
> +        command = shlex.split(cmd)
Excellent work, thank you :)

2022-05-05 21:14 UTC, kousu reviewed
If I click "Comment" does that remove my "Request Changes"?

2022-05-05 21:14 UTC, kousu approved these changes
Evidently not :roll_eyes: 

Here's your :heavy_check_mark:

2022-05-11 22:13 UTC, po09i commented on shimmingtoolbox/utils.py
> +        command = shlex.split(cmd)
Fixed here: [539a5b7](https://github.com/shimming-toolbox/shimming-toolbox/pull/387/commits/539a5b7f4942adaf28afe553984f303301abc9fb)

2022-05-11 22:41 UTC, merged