Shimmed field map plotting for real time shimming by averaging over time dimension
shimming-toolbox/shimming-toolbox pull request #463
Opened 2023-06-28 20:29 UTC by 4rnaudB

## Checklist

- [ ] I've given this PR a concise, self-descriptive, and meaningful title
- [ ] I've applied the relevant labels to this PR
- [ ] I've added relevant tests for my contribution
- [ ] I've updated the documentation and/or added correct docstrings
- [ ] I've assigned a reviewer

## Description

- Correction of an error for `shimmingtoolbox/shim/sequencer.py at line 931` where the return order was opposite to what was expected in the code

- Adaptation of ShimSequencer.plot_full_mask() for RealTimeSequencer. The shimmed field map was averaged over the fourth dimension (time) and fifth (not sure what it is @po09i). Here is the current state result from a subject using first order real time shimming (results seem too good):

<img width="770" alt="image" src="https://github.com/shimming-toolbox/shimming-toolbox/assets/55560824/4a590b27-7771-44c4-924e-074226dfdd29">

2023-06-29 15:00 UTC, 4rnaudB commented
The plotting function had to be moved to DEBUG only mode since some tests for real time shimming don't provide the output path required to save the figure. The problem is DEBUG mode is not accessible from the GUI. If we don't want to generate the figure automatically, we can keep the tests like this, but if we want to generate it everytime real time shimming is run (like in dynamic shimming) we should maybe modify the test to give an output path or make the default output path different than None?

2023-06-29 15:25 UTC, po09i commented
If the figure is a figure that should be output to the user every time, we can move it outside of the `DEBUG` condition. We should still wrap it within a `path_output` condition. The reasoning is that if sequencer is used as an API, we do not necessarily want to output figures, but specifying a path would write it to a file. When using the CLI, the default path exists and we should therefore have a oath to write to.

2023-06-29 15:31 UTC, po09i commented
> The shimmed field map was averaged over the fourth dimension (time) and fifth (not sure what it is @po09i).

The 4th dimension is indeed time while the 5th dimension is each shim group (for slice-wise shimming, there would be one shim group per slice). Therefore the 5 dimension array tells you the 3D corrected volume for each time points and for each shim group.

2023-06-29 15:32 UTC, 4rnaudB commented
The equivalent figure is plotted by default when using dynamic shimming

2023-06-29 15:40 UTC, 4rnaudB commented
> The 4th dimension is indeed time while the 5th dimension is each shim group (for slice-wise shimming, there would be one shim group per slice). Therefore the 5 dimension array tells you the 3D corrected volume for each time points and for each shim group.

So does it make sense to average the 5th dimension to get an average corrected field map?

2023-06-29 19:22 UTC, 4rnaudB commented
I summed the fifth dimension considering the weighed mask and kept the average for the time dimension. New results:
<img width="769" alt="image" src="https://github.com/shimming-toolbox/shimming-toolbox/assets/55560824/2d1b2401-67bc-48eb-ad7e-75840e617d02">

2023-06-29 20:35 UTC, po09i commented
There is an issue with averaging the 5th dimension. It does not tell the full story. We are acquiring a fieldmap that we expect to vary by a small amount between timepoints. The role of the realtime correction is to reduce the variation between different timepoints. By averaging each timepoints, we lose this information. I think we also need a map that describes by how much each points change over the time dimension (std for example).

2023-07-03 14:24 UTC, 4rnaudB commented
Yes, Julien asked to plot a heatmap of the STD over time to show the time correction effect. If we want, to compare to dynamic shimming, should we have an option to plot this for dynamic shimming as well if the field map is 4D?

2023-07-03 21:16 UTC, po09i commented
> should we have an option to plot this for dynamic shimming as well if the field map is 4D?

I don't think we should have this for non real-time shimming.

2023-07-07 20:36 UTC, 4rnaudB commented
@po09i The inconsistency issue is fixed, we just need to decide when and where we should plot these figures.

2023-07-10 18:12 UTC, po09i commented
I think if they do not take too long, we should always output them as they are what tells how good the shim is. As for where, they should be in "path_output" and ideally be calculated after the text file is written.

2023-07-10 19:05 UTC, 4rnaudB commented
> The plotting function had to be moved to DEBUG only mode since some tests for real-time shimming don't provide the output path required to save the figure

So I should make the output path mandatory and change the tests?

2023-07-10 21:53 UTC, po09i commented
The code looks good!, how long does it take to generate and plot the figures that you added?

2023-07-10 21:54 UTC, po09i commented
> So I should make change the sequencer tests to have them set an output path?

I would do as you did and output them if an `output_path` is provided

2023-07-11 13:26 UTC, 4rnaudB commented
> how long does it take to generate and plot the figures that you added?
<img width="316" alt="image" src="https://github.com/shimming-toolbox/shimming-toolbox/assets/55560824/f141a544-0803-4d1d-ad8f-0682e0e573ec">
<img width="316" alt="image" src="https://github.com/shimming-toolbox/shimming-toolbox/assets/55560824/87f50924-9ebf-46ff-a363-452d6df9a39e">

2023-07-11 13:58 UTC, po09i requested changes

2023-07-11 13:58 UTC, po09i commented on shimmingtoolbox/shim/sequencer.py
> +        print("---------------------------------------------------------------- \n SAVING")
```suggestion
```

If you want to print something, use `logger.info("")`

2023-07-11 13:58 UTC, po09i commented on shimmingtoolbox/shim/sequencer.py
> +        print("---------------------------------------------------------------- \n SAVING")
However in this case I would not output anything since there could be multiple plots that could output "saving".

2023-07-11 14:36 UTC, po09i approved these changes

2023-07-11 15:49 UTC, merged