Split coils and scaner order for optimization + alow specific scaner orders for each
shimming-toolbox/shimming-toolbox pull request #484
Opened 2023-09-18 21:32 UTC by 4rnaudB

## Checklist

- [ ] I've given this PR a concise, self-descriptive, and meaningful title
- [ ] I've linked relevant issues in the PR body
- [ ] I've applied the relevant labels to this PR
- [ ] I've added relevant tests for my contribution
- [ ] I've updated the documentation and/or added correct docstrings
- [ ] I've assigned a reviewer

## Description
PR to split the coefficients' optimization between static and RIRO to allow users to optimize both coefficient types with different coils and scanner order. This PR will also implement the possibility of selecting specific scanner orders to use instead of using every scanner order below the selected one. 

## Linked issues
#471

2023-10-02 20:06 UTC, po09i reviewed
In terms of style, try to have spaces between operations (`2 * 2 `rather than `2*2`).

For GE, you can do something very similar to what you have done for Siemens.

2023-10-02 20:06 UTC, po09i commented on shimmingtoolbox/cli/b0shim.py
> +        if any(order<-1 or order>2 for order in orders):
Use `AVAILABLE_ORDERS` to check so that if we add order 3, we only have to change that that list rather than the parse_order function ad well "`order in AVAILABLE_ORDER`"

2023-10-02 20:06 UTC, po09i commented on shimmingtoolbox/cli/b0shim.py
```suggestion


```

2023-10-02 20:06 UTC, po09i commented on shimmingtoolbox/cli/b0shim.py
> +    index = 0
Add comments mentioning what you are doing

2023-10-02 20:06 UTC, po09i commented on shimmingtoolbox/cli/b0shim.py
> +                        if (order != -1 and (str(order) in coil_indexes_riro[coil.name]
Is there a problem if the name of the coil is the same for 2 different coils? Maybe we should add a check that all coil names must be different.

2023-10-02 20:06 UTC, po09i commented on shimmingtoolbox/coils/siemens_basis.py
this file should not exist anymore, `siemens_basis` is now part of `sphere_harm_basis`

2023-10-02 20:06 UTC, po09i commented on shimmingtoolbox/coils/spher_harm_basis.py
> +        range_per_order[order] = list(range(index, index+(order*2 +1)))
Siemens' order 3 does not contain all 7 channels (I think they did not implement 2 of them). Therefore I'm a bit reluctant to modifying everything based on `order * 2 + 1`since it will break with order 3.

2023-10-02 20:06 UTC, po09i commented on shimmingtoolbox/coils/spher_harm_basis.py
> +def get_flip_matrix(shim_cs='ras', orders=(1,2), manufacturer=None, xyz=False):
Since you added orders as an option, `xyz` does not make sense anymore (equivalent to orders=(1,))

2023-10-02 20:06 UTC, po09i commented on shimmingtoolbox/shim/shim_utils.py
> +            flip_mat[:8] = get_flip_matrix(shim_cs[manufacturer], orders, manufacturer=manufacturer)
same comment as above, if orders is (1,), it is redundant to `xyz`

2023-10-03 19:08 UTC, 4rnaudB commented on shimmingtoolbox/cli/b0shim.py
> +                        if (order != -1 and (str(order) in coil_indexes_riro[coil.name]
There would be a problem yes, but the verification should probably be done at the input level and not once al the shimming is done right?

2023-10-04 15:54 UTC, 4rnaudB commented on shimmingtoolbox/cli/b0shim.py
> +                        if (order != -1 and (str(order) in coil_indexes_riro[coil.name]
fixed in [7f7c64f](https://github.com/shimming-toolbox/shimming-toolbox/pull/484/commits/7f7c64f6620861b8e7a78da30c8c6353ae88b4bb)

2023-10-11 20:47 UTC, po09i commented on shimmingtoolbox/cli/b0shim.py
> +                        if (order != -1 and (str(order) in coil_indexes_riro[coil.name]
I see you made a check based on if the coil has the same path. However, if the "name" of the coil is the same, there would still be an error (`coil.name` would refer to the same coil though they are different coils)

2023-10-11 20:56 UTC, 4rnaudB commented on shimmingtoolbox/cli/b0shim.py
> +                        if (order != -1 and (str(order) in coil_indexes_riro[coil.name]
not sure what you mean because my test verifies if some coils have the same name

2023-10-11 20:58 UTC, 4rnaudB commented on shimmingtoolbox/cli/b0shim.py
> +                        if (order != -1 and (str(order) in coil_indexes_riro[coil.name]
```
if len(coils) != len(set(coils)):
        raise ValueError("Coils must be unique. Make sure different coils have different names.")
```
Is a verification based on coil names

2023-10-11 21:03 UTC, po09i reviewed
We should have an example config file for custom coils as well now that they are defined differently.

We should have the same behaviour for the --scanner-coil-order-riro (something as --scanner-coil-order when not defined) and for --coil-riro (same thing as --coil when not defined). I do not believe this is the case.. This has me thinking, what do we do if we do not want to shim static, or if we do not want to shim riro? What would be the inputs?

2023-10-11 21:06 UTC, po09i commented on shimmingtoolbox/cli/b0shim.py
> +                        if (order != -1 and (str(order) in coil_indexes_riro[coil.name]
This is a verification based on the file name/path. However, there is a `name` key in the .json file that could still be the same even if they have different paths.
![Screenshot 2023-10-11 at 5 06 39 PM](https://github.com/shimming-toolbox/shimming-toolbox/assets/47249340/80b09e69-2638-4cc7-8035-169e4c07aaf3)

2023-10-11 21:25 UTC, 4rnaudB commented on shimmingtoolbox/cli/b0shim.py
> +                        if (order != -1 and (str(order) in coil_indexes_riro[coil.name]
True, don't know why I put it there, now fixed

2023-10-11 21:29 UTC, 4rnaudB commented
>what do we do if we do not want to shim static, or if we do not want to shim riro? What would be the inputs?

If you don't want to shim riro, you use dynamic shim. If you don't want to shim static, it's not a real possibility, but when would you not want to shim static?

2023-10-11 21:41 UTC, po09i commented
The was a problem for coils other than the Prisma, I modified it and it should work now. However, I suggest testing for them by modifying the manufacturer_model_name to something other than the Prisma, you can also test for GE or Philips using this method and making sure the coefficients are the same as what you would get on master. We should probably tests that simply modify the sidecar and simulate data from other manufacturers.

2023-12-21 16:29 UTC, po09i commented on shimmingtoolbox/coils/coil.py
> +    # ! Modify description if everything works
Description was modified?

2023-12-21 16:29 UTC, po09i commented on shimmingtoolbox/coils/coil.py
> +    # ! Modified
Remove comment

2023-12-21 16:29 UTC, po09i commented on shimmingtoolbox/coils/coil.py
> +    # ! Modify description if everything works
Remove comment

2023-12-21 16:29 UTC, po09i commented on shimmingtoolbox/coils/spher_harm_basis.py
> +    # range_per_order = {1: list(range(3)), 2: list(range(3, 8))}
Remove comment

2023-12-21 16:29 UTC, po09i commented on shimmingtoolbox/optimizer/basic_optimizer.py
> +        #! Modified
Remove comment

2023-12-22 18:37 UTC, po09i requested changes

2023-12-22 18:37 UTC, po09i commented on shimmingtoolbox/coils/spher_harm_basis.py
> +def scaled_spher_harm(x, y, z, all_orders, shim_cs='ras'):
If the input spherical harmonic order is 2, the scaling factor that gets applied is wrong. (scaling_factors always has 8 coefficients)

2024-01-09 21:52 UTC, po09i approved these changes
LGTM!

2024-01-09 21:55 UTC, merged