Add FSL license for prelude
shimming-toolbox/shimming-toolbox pull request #51
Opened 2020-07-31 17:42 UTC by po09i

Prelude is an external dependency and should have its own license. This PR adds FSL's license.

2020-07-31 18:43 UTC, gaspardcereza approved these changes

2020-08-01 15:29 UTC, jcohenadad requested changes
we don't actually bundle FSL's prelude in this repository but in this [other repository](https://github.com/shimming-toolbox/binaries).

what is the reason you'd like to add the license here?

2020-08-03 16:20 UTC, po09i commented
I thought it should be bundled where we use it but I can do the same PR in this [binaries repo](https://github.com/shimming-toolbox/binaries) instead.

2020-08-03 20:15 UTC, jcohenadad commented
so i guess we can close after you create the PR in the other repos and cross-ref here--

2020-08-03 21:09 UTC, po09i commented
PR moved to [binaries repo](https://github.com/shimming-toolbox/binaries/pull/1) 
This can be closed

2020-08-03 21:09 UTC, closed without merging